/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    AlertBar: typeof import('./src/components/AlertBar.vue')['default']
    CommonState: typeof import('./src/components/common/State.vue')['default']
    CommonTile: typeof import('./src/components/common/Tile.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GroupCard: typeof import('./src/components/group/Card.vue')['default']
    GroupChip: typeof import('./src/components/group/Chip.vue')['default']
    GroupList: typeof import('./src/components/group/List.vue')['default']
    GroupPage: typeof import('./src/components/group/Page.vue')['default']
    LoginPage: typeof import('./src/components/login/Page.vue')['default']
    NotificationBar: typeof import('./src/components/NotificationBar.vue')['default']
    ProcessChip: typeof import('./src/components/process/Chip.vue')['default']
    ProcessDetails: typeof import('./src/components/process/Details.vue')['default']
    ProcessLog: typeof import('./src/components/process/Log.vue')['default']
    ProcessPage: typeof import('./src/components/process/Page.vue')['default']
    ProcessRow: typeof import('./src/components/process/Row.vue')['default']
    ProcessState: typeof import('./src/components/common/State.vue')['default']
    ProcessTile: typeof import('./src/components/common/Tile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupervisorCard: typeof import('./src/components/supervisor/Card.vue')['default']
    SupervisorChip: typeof import('./src/components/supervisor/Chip.vue')['default']
    SupervisorList: typeof import('./src/components/supervisor/List.vue')['default']
    SupervisorPage: typeof import('./src/components/supervisor/Page.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
