# multivisor demonstration
# $ docker-compose build --parallel
# $ docker-compose up
# Point your web browser to http://localhost:22000

version: '3'
services:
  lid001:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    command: ["supervisord", "-c", "/etc/supervisord/lid001.conf"]
    ports:
      - 9011:9001
    volumes:
      - ./docker/supervisord/lid001.conf:/etc/supervisord/lid001.conf
  lid002:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    command: ["supervisord", "-c", "/etc/supervisord/lid002.conf"]
    ports:
      - 9021:9001
      - 5000:5000
    volumes:
      - ./docker/supervisord/lid002.conf:/etc/supervisord/lid002.conf
  baslid001:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    command: ["supervisord", "-c", "/etc/supervisord/baslid001.conf"]
    ports:
      - 9031:9001
    volumes:
      - ./docker/supervisord/baslid001.conf:/etc/supervisord/baslid001.conf
  multivisor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    #command: ["multivisor", "-c", "/etc/multivisor.conf"]
    command:
    - watchmedo
    - auto-restart
    - -Rv
    - --patterns
    - '*.py;*.html'
    - multivisor
    - --
    - -c
    - /etc/multivisor.conf
    - --log-level=DEBUG
    ports:
      - 22000:22000
    volumes:
      - ./docker/multivisor/multivisor.conf:/etc/multivisor.conf
      - ./multivisor/:/usr/app/multivisor/multivisor
  web:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 22001:80
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./multivisor/server/static/:/multivisor/static