#!/usr/bin/env python

import sys
import time

name = ' '.join([sys.argv[0].rsplit('/', 1)[1]] + sys.argv[1:])

die_in = int(sys.argv[1]) if len(sys.argv) > 1 else 10

i = 0
start = time.time()
while True:
  if die_in < time.time() - start:
    exit(123)
  print '%s %d' % (name, i)
  i += 1
  time.sleep(0.1)

